### ISSUE TITLE
subprocess.CalledProcessError: Command 'make lib' returned non-zero exit status 1

### ISSUE THREAD

**Issue by PratyushTripathy** [cmla/ransac#3]
Hi, 
I tried installing using the pip command:
`python -m pip install ransac`
it throws the following error:

<details><summary>Details</summary>
<p>
Collecting ransac
  Using cached https://files.pythonhosted.org/packages/7f/b2/e0683d0cc645a0bf35372cb732dc6bc10644bf9b1704dac0ed5c4a6d8f33/ransac-1.0.2.tar.gz
Requirement already satisfied: numpy in c:\python36\lib\site-packages (from ransac) (1.18.2)
Installing collected packages: ransac
  Running setup.py install for ransac ... error
    Complete output from command C:\Python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\pip-install-_y_dpp0n\\ransac\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-record-ynqwhj_2\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib
    copying ransac.py -> build\lib
    The system cannot find the path specified.
    mkdir -p lib
    cc -march=native -O3 -std=gnu99 -fPIC -shared -o lib/libransac.so c/ransac.c
    process_begin: CreateProcess(NULL, cc -march=native -O3 -std=gnu99 -fPIC -shared -o lib/libransac.so c/ransac.c, ...) failed.
    make (e=2): The system cannot find the file specified.
    make: *** [lib/libransac.so] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-install-_y_dpp0n\ransac\setup.py", line 52, in <module>
        'build_py': CustomBuildPy})
      File "C:\Python36\lib\site-packages\setuptools\__init__.py", line 143, in setup
        return distutils.core.setup(**attrs)
      File "C:\Python36\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Python36\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Python36\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Python36\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\Python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Python36\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-install-_y_dpp0n\ransac\setup.py", line 31, in run
        subprocess.check_call("make lib", shell=True)
      File "C:\Python36\lib\subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'make lib' returned non-zero exit status 2.

    ----------------------------------------
Command "C:\Python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\pip-install-_y_dpp0n\\ransac\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-record-ynqwhj_2\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\ADMINI~1\AppData\Local\Temp\2\pip-install-_y_dpp0n\ransac\
</p>
</details>

**Comment by carlodef** [comment]
Hi,
It seems that your system doesn't find `make`. You need to install `GNU make` before running `pip`.

**Comment by PratyushTripathy** [comment]
@carlodef sorted. Thanks!
