### ISSUE TITLE
ERROR: Failed building wheel for ransac

### ISSUE THREAD

**Issue by 404notfound-3** [cmla/ransac#4]
Hii, I am getting this error while installing ransac.
python version - 3.7.4 (anaconda)

```

(base) C:\Users\sword>pip install ransac
Collecting ransac
  Using cached ransac-1.0.2.tar.gz (31 kB)
Requirement already satisfied: numpy in c:\users\sword\anaconda3\lib\site-packages (from ransac) (1.18.5)
Building wheels for collected packages: ransac
  Building wheel for ransac (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\sword\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\sword\\AppData\\Local\\Temp\\pip-install-hhnshu8j\\ransac\\setup.py'"'"'; __file__='"'"'C:\\Users\\sword\\AppData\\Local\\Temp\\pip-install-hhnshu8j\\ransac\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\sword\AppData\Local\Temp\pip-wheel-apxrv6n8'
       cwd: C:\Users\sword\AppData\Local\Temp\pip-install-hhnshu8j\ransac\
  Complete output (37 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  copying ransac.py -> build\lib
  'make' is not recognized as an internal or external command,
  operable program or batch file.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\sword\AppData\Local\Temp\pip-install-hhnshu8j\ransac\setup.py", line 52, in <module>
      'build_py': CustomBuildPy})
    File "C:\Users\sword\Anaconda3\lib\site-packages\setuptools\__init__.py", line 165, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\sword\Anaconda3\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\sword\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\sword\Anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\sword\Anaconda3\lib\site-packages\wheel\bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "C:\Users\sword\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\sword\Anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\sword\Anaconda3\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\sword\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\sword\Anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\sword\AppData\Local\Temp\pip-install-hhnshu8j\ransac\setup.py", line 31, in run
      subprocess.check_call("make lib", shell=True)
    File "C:\Users\sword\Anaconda3\lib\subprocess.py", line 347, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'make lib' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for ransac
  Running setup.py clean for ransac
Failed to build ransac
Installing collected packages: ransac
    Running setup.py install for ransac ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\sword\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\sword\\AppData\\Local\\Temp\\pip-install-hhnshu8j\\ransac\\setup.py'"'"'; __file__='"'"'C:\\Users\\sword\\AppData\\Local\\Temp\\pip-install-hhnshu8j\\ransac\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\sword\AppData\Local\Temp\pip-record-ptsqk026\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\sword\Anaconda3\Include\ransac'
         cwd: C:\Users\sword\AppData\Local\Temp\pip-install-hhnshu8j\ransac\
    Complete output (39 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib
    copying ransac.py -> build\lib
    'make' is not recognized as an internal or external command,
    operable program or batch file.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\sword\AppData\Local\Temp\pip-install-hhnshu8j\ransac\setup.py", line 52, in <module>
        'build_py': CustomBuildPy})
      File "C:\Users\sword\Anaconda3\lib\site-packages\setuptools\__init__.py", line 165, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\sword\Anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\sword\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\sword\Anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\sword\Anaconda3\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\sword\Anaconda3\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\Users\sword\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\sword\Anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\sword\Anaconda3\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Users\sword\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\sword\Anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\sword\AppData\Local\Temp\pip-install-hhnshu8j\ransac\setup.py", line 31, in run
        subprocess.check_call("make lib", shell=True)
      File "C:\Users\sword\Anaconda3\lib\subprocess.py", line 347, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'make lib' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\sword\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\sword\\AppData\\Local\\Temp\\pip-install-hhnshu8j\\ransac\\setup.py'"'"'; __file__='"'"'C:\\Users\\sword\\AppData\\Local\\Temp\\pip-install-hhnshu8j\\ransac\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\sword\AppData\Local\Temp\pip-record-ptsqk026\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\sword\Anaconda3\Include\ransac' Check the logs for full command output.
```

**Comment by carlodef** [comment]
Hi, your error traceback says

    'make' is not recognized as an internal or external command,

Is `make` available on your system? If not, then that is the issue. You need to install GNU make.

**Comment by 404notfound-3** [comment]
Thanks @carlodef
