### ISSUE TITLE
Pip install issue

### ISSUE THREAD

**Issue by trahloff** [cmla/ransac#6]
Hi, 

I was trying to install this package via pip in a clean and newly created Conda environment.

~~~bash
$ pip install ransac
~~~

Unfortunately, I'm running into the following issue:

~~~log
Collecting ransac
  Using cached ransac-1.0.4.tar.gz (31 kB)
Collecting numpy
  Using cached numpy-1.22.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
Building wheels for collected packages: ransac
  Building wheel for ransac (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/tobias/anaconda3/envs/ransac-test/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xjg2n9p2/ransac_c74a918753a54f35ab16a80e88281a3f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xjg2n9p2/ransac_c74a918753a54f35ab16a80e88281a3f/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-_w8_u_c0
       cwd: /tmp/pip-install-xjg2n9p2/ransac_c74a918753a54f35ab16a80e88281a3f/
  Complete output (42 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  copying ransac.py -> build/lib
  mkdir -p lib
  cc -march=native -O3 -mno-avx512f -fPIC -shared -o lib/libransac.so c/ransac.c
  cc1: error: bad value (‘tigerlake’) for ‘-march=’ switch
  cc1: note: valid arguments to ‘-march=’ switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server cascadelake bonnell atom silvermont slm goldmont goldmont-plus tremont knl knm x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 znver2 btver1 btver2 native
  cc1: error: bad value (‘tigerlake’) for ‘-mtune=’ switch
  cc1: note: valid arguments to ‘-mtune=’ switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server cascadelake bonnell atom silvermont slm goldmont goldmont-plus tremont knl knm intel x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 znver2 btver1 btver2 generic native
  make: *** [Makefile:22: lib/libransac.so] Error 1
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-xjg2n9p2/ransac_c74a918753a54f35ab16a80e88281a3f/setup.py", line 40, in <module>
      setup(name="ransac",
    File "/home/tobias/anaconda3/envs/ransac-test/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/home/tobias/anaconda3/envs/ransac-test/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/tobias/anaconda3/envs/ransac-test/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/tobias/anaconda3/envs/ransac-test/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/tobias/anaconda3/envs/ransac-test/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/home/tobias/anaconda3/envs/ransac-test/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/tobias/anaconda3/envs/ransac-test/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/tobias/anaconda3/envs/ransac-test/lib/python3.9/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/tobias/anaconda3/envs/ransac-test/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/tobias/anaconda3/envs/ransac-test/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-xjg2n9p2/ransac_c74a918753a54f35ab16a80e88281a3f/setup.py", line 31, in run
      subprocess.check_call("make lib", shell=True)
    File "/home/tobias/anaconda3/envs/ransac-test/lib/python3.9/subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'make lib' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for ransac
  Running setup.py clean for ransac
Failed to build ransac
Installing collected packages: numpy, ransac
    Running setup.py install for ransac ... error
    ERROR: Command errored out with exit status 1:
     command: /home/tobias/anaconda3/envs/ransac-test/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xjg2n9p2/ransac_c74a918753a54f35ab16a80e88281a3f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xjg2n9p2/ransac_c74a918753a54f35ab16a80e88281a3f/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-7aid119n/install-record.txt --single-version-externally-managed --compile --install-headers /home/tobias/anaconda3/envs/ransac-test/include/python3.9/ransac
         cwd: /tmp/pip-install-xjg2n9p2/ransac_c74a918753a54f35ab16a80e88281a3f/
    Complete output (44 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib
    copying ransac.py -> build/lib
    mkdir -p lib
    cc -march=native -O3 -mno-avx512f -fPIC -shared -o lib/libransac.so c/ransac.c
    cc1: error: bad value (‘tigerlake’) for ‘-march=’ switch
    cc1: note: valid arguments to ‘-march=’ switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server cascadelake bonnell atom silvermont slm goldmont goldmont-plus tremont knl knm x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 znver2 btver1 btver2 native
    cc1: error: bad value (‘tigerlake’) for ‘-mtune=’ switch
    cc1: note: valid arguments to ‘-mtune=’ switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server cascadelake bonnell atom silvermont slm goldmont goldmont-plus tremont knl knm intel x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 znver2 btver1 btver2 generic native
    make: *** [Makefile:22: lib/libransac.so] Error 1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xjg2n9p2/ransac_c74a918753a54f35ab16a80e88281a3f/setup.py", line 40, in <module>
        setup(name="ransac",
      File "/home/tobias/anaconda3/envs/ransac-test/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/tobias/anaconda3/envs/ransac-test/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/tobias/anaconda3/envs/ransac-test/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/tobias/anaconda3/envs/ransac-test/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/tobias/anaconda3/envs/ransac-test/lib/python3.9/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/tobias/anaconda3/envs/ransac-test/lib/python3.9/distutils/command/install.py", line 546, in run
        self.run_command('build')
      File "/home/tobias/anaconda3/envs/ransac-test/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/tobias/anaconda3/envs/ransac-test/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/tobias/anaconda3/envs/ransac-test/lib/python3.9/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/tobias/anaconda3/envs/ransac-test/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/tobias/anaconda3/envs/ransac-test/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-xjg2n9p2/ransac_c74a918753a54f35ab16a80e88281a3f/setup.py", line 31, in run
        subprocess.check_call("make lib", shell=True)
      File "/home/tobias/anaconda3/envs/ransac-test/lib/python3.9/subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'make lib' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/tobias/anaconda3/envs/ransac-test/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xjg2n9p2/ransac_c74a918753a54f35ab16a80e88281a3f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xjg2n9p2/ransac_c74a918753a54f35ab16a80e88281a3f/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-7aid119n/install-record.txt --single-version-externally-managed --compile --install-headers /home/tobias/anaconda3/envs/ransac-test/include/python3.9/ransac Check the logs for full command output.
~~~

Any idea how to fix this? Thanks a lot!

**Comment by carlodef** [comment]
Hi @trahloff, thanks for reporting this issue!

The error is
```    
cc -march=native -O3 -mno-avx512f -fPIC -shared -o lib/libransac.so c/ransac.c
cc1: error: bad value (‘tigerlake’) for ‘-march=’ switch
```

Which C compiler are you using ? Please run `cc --version` and share the output.

You probably just need to update it, with for example `sudo apt install gcc-10`
