### ISSUE TITLE
Issue installing the package

### ISSUE THREAD

**Issue by mcafier** [cmla/ransac#7]
Hi, I'm trying to install your package on conda (I'm on Windows), but I came across an issue that I can't seem to solve. 

When I run the following command :

`pip install ransac`

I get the following error : 

```
Collecting ransac
  Using cached ransac-1.0.4.tar.gz (31 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in c:\users\mcafier\anaconda3\lib\site-packages (from ransac) (1.20.3)
Building wheels for collected packages: ransac
  Building wheel for ransac (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib
      copying ransac.py -> build\lib
      'make' n'est pas reconnu en tant que commande interne
      ou externe, un programme ex‚cutable ou un fichier de commandes.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\mcafier\AppData\Local\Temp\pip-install-n7l4beoa\ransac_7196d452e6fc4313a7ceff2007749f62\setup.py", line 40, in <module>
          setup(name="ransac",
        File "C:\Users\mcafier\anaconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\mcafier\anaconda3\lib\distutils\core.py", line 148, in setup
          dist.run_commands()
        File "C:\Users\mcafier\anaconda3\lib\distutils\dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "C:\Users\mcafier\anaconda3\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\mcafier\anaconda3\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "C:\Users\mcafier\anaconda3\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\mcafier\anaconda3\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\mcafier\anaconda3\lib\distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
        File "C:\Users\mcafier\anaconda3\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\mcafier\anaconda3\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\mcafier\AppData\Local\Temp\pip-install-n7l4beoa\ransac_7196d452e6fc4313a7ceff2007749f62\setup.py", line 31, in run
          subprocess.check_call("make lib", shell=True)
        File "C:\Users\mcafier\anaconda3\lib\subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command 'make lib' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ransac
  Running setup.py clean for ransac
Failed to build ransac
Installing collected packages: ransac
  Running setup.py install for ransac ... error
  error: subprocess-exited-with-error

  × Running setup.py install for ransac did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build\lib
      copying ransac.py -> build\lib
      'make' n'est pas reconnu en tant que commande interne
      ou externe, un programme ex‚cutable ou un fichier de commandes.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\mcafier\AppData\Local\Temp\pip-install-n7l4beoa\ransac_7196d452e6fc4313a7ceff2007749f62\setup.py", line 40, in <module>
          setup(name="ransac",
        File "C:\Users\mcafier\anaconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\mcafier\anaconda3\lib\distutils\core.py", line 148, in setup
          dist.run_commands()
        File "C:\Users\mcafier\anaconda3\lib\distutils\dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "C:\Users\mcafier\anaconda3\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\mcafier\anaconda3\lib\site-packages\setuptools\command\install.py", line 61, in run
          return orig.install.run(self)
        File "C:\Users\mcafier\anaconda3\lib\distutils\command\install.py", line 546, in run
          self.run_command('build')
        File "C:\Users\mcafier\anaconda3\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\mcafier\anaconda3\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\mcafier\anaconda3\lib\distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
        File "C:\Users\mcafier\anaconda3\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\mcafier\anaconda3\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\mcafier\AppData\Local\Temp\pip-install-n7l4beoa\ransac_7196d452e6fc4313a7ceff2007749f62\setup.py", line 31, in run
          subprocess.check_call("make lib", shell=True)
        File "C:\Users\mcafier\anaconda3\lib\subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command 'make lib' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> ransac

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

My computer is setup in french, so I'll translate what the french part says : 
` "make" is not recognized as an internal or external command operable program or batch file`

Do you have any idea how I could solve this problem ? Thank you !

**Comment by mcafier** [comment]
After installing the following package :
`conda install -c anaconda make`

I re-openened my terminal to install your package again : 
`pip install ransac`

It looks like I got a bit further, but not too much : 

```
Collecting ransac
  Using cached ransac-1.0.4.tar.gz (31 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in c:\users\mcafier\anaconda3\lib\site-packages (from ransac) (1.20.3)
Building wheels for collected packages: ransac
  Building wheel for ransac (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [43 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib
      copying ransac.py -> build\lib
      /usr/bin/sh: cl.exe: command not found
      mkdir -p lib
      cl.exe -march=native -O3 -mno-avx512f -std=gnu99 -fPIC -shared -o lib/libransac.so c/ransac.c
      process_begin: CreateProcess(NULL, cl.exe -march=native -O3 -mno-avx512f -std=gnu99 -fPIC -shared -o lib/libransac.so c/ransac.c, ...) failed.
      make (e=2): Le fichier spécifié est introuvable.

      make: *** [Makefile:22: lib/libransac.so] Error 2
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\mcafier\AppData\Local\Temp\pip-install-b7f6lsj7\ransac_abf821f209a6423b8fc88cf6e8920fc3\setup.py", line 40, in <module>
          setup(name="ransac",
        File "C:\Users\mcafier\anaconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\mcafier\anaconda3\lib\distutils\core.py", line 148, in setup
          dist.run_commands()
        File "C:\Users\mcafier\anaconda3\lib\distutils\dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "C:\Users\mcafier\anaconda3\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\mcafier\anaconda3\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "C:\Users\mcafier\anaconda3\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\mcafier\anaconda3\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\mcafier\anaconda3\lib\distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
        File "C:\Users\mcafier\anaconda3\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\mcafier\anaconda3\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\mcafier\AppData\Local\Temp\pip-install-b7f6lsj7\ransac_abf821f209a6423b8fc88cf6e8920fc3\setup.py", line 31, in run
          subprocess.check_call("make lib", shell=True)
        File "C:\Users\mcafier\anaconda3\lib\subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command 'make lib' returned non-zero exit status 2.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ransac
  Running setup.py clean for ransac
Failed to build ransac
Installing collected packages: ransac
  Running setup.py install for ransac ... error
  error: subprocess-exited-with-error

  × Running setup.py install for ransac did not run successfully.
  │ exit code: 1
  ╰─> [45 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build\lib
      copying ransac.py -> build\lib
      /usr/bin/sh: cl.exe: command not found
      mkdir -p lib
      cl.exe -march=native -O3 -mno-avx512f -std=gnu99 -fPIC -shared -o lib/libransac.so c/ransac.c
      process_begin: CreateProcess(NULL, cl.exe -march=native -O3 -mno-avx512f -std=gnu99 -fPIC -shared -o lib/libransac.so c/ransac.c, ...) failed.
      make (e=2): Le fichier spécifié est introuvable.

      make: *** [Makefile:22: lib/libransac.so] Error 2
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\mcafier\AppData\Local\Temp\pip-install-b7f6lsj7\ransac_abf821f209a6423b8fc88cf6e8920fc3\setup.py", line 40, in <module>
          setup(name="ransac",
        File "C:\Users\mcafier\anaconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\mcafier\anaconda3\lib\distutils\core.py", line 148, in setup
          dist.run_commands()
        File "C:\Users\mcafier\anaconda3\lib\distutils\dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "C:\Users\mcafier\anaconda3\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\mcafier\anaconda3\lib\site-packages\setuptools\command\install.py", line 61, in run
          return orig.install.run(self)
        File "C:\Users\mcafier\anaconda3\lib\distutils\command\install.py", line 546, in run
          self.run_command('build')
        File "C:\Users\mcafier\anaconda3\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\mcafier\anaconda3\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\mcafier\anaconda3\lib\distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
        File "C:\Users\mcafier\anaconda3\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\mcafier\anaconda3\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\mcafier\AppData\Local\Temp\pip-install-b7f6lsj7\ransac_abf821f209a6423b8fc88cf6e8920fc3\setup.py", line 31, in run
          subprocess.check_call("make lib", shell=True)
        File "C:\Users\mcafier\anaconda3\lib\subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command 'make lib' returned non-zero exit status 2.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> ransac

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```
It looks like the installation wants to use Linux syntax, but I'm on Windows. 
I'm going to try to find an alternative to your package in the meantime. Thank you again 👍

**Comment by muthukumaranR** [comment]
export CFLAGS='-std=c99'  and then installing ransac worked for me
